version : "3"

services:
  flaskapp:
    build: .
    restart : always
    ports :
      - "5000:5000"
    depends_on:
      - db
  db: 
    image: postgres
    environment: 
      POSTGRES_DB : database
      POSTGRES_USER : user
      POSTGRES_PASSWORD: password

    restart: always
    
